config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :dishes do
      member do
        get :select_regions
        post :save_regions
      end
    end
    resources :bottle_racks do
      member do
        post :get_info
      end
    end
    resources :wines do
      resources :millesimes, except: %i[index] do
        resources :wlogs, except: %i[index show] do
          member do
            get :select_rack
            get :select_rack2
            post :save_rack
          end
        end
      end
    end
    resources :providers
    resources :producers
    resources :colors, except: %i[show] do
      collection do
        get :stats
      end
    end
    resources :countries, except: %i[show] do
      collection do
        get :stats
      end
      resources :regions do
        collection do
          get :country_stats
        end
        member do
          get :stats
          post :wine_list_by_color
        end
      end
    end

    get 'admin/main'
    get 'admin/book'
    get 'admin/stats'
    get 'admin/search'
    get 'admin/preferences'
    post 'admin/set_preferences'
    get '/:locale' => 'admin#main'
    root 'admin#main'
  end
end

app/models/producer.rb
class Producer < ApplicationRecord
  belongs_to :country
  has_many :wines

  validates :name, presence: true
  validates :web, url: { scheme: %w[http https] }, allow_blank: true
  validates :email, format: /@/, allow_blank: true

  scope :by_name, -> { order(:name) }
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :at_producer, only: %i[show edit update destroy]

  # GET /producers
  # GET /producers.json
  def index
    @producers = Producer.by_name.page(params[:page])
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
    @millesimes_to_drink = Millesime.with_bottles.from_producer(@producer)
    @drunk_millesimes = Millesime.without_bottles.from_producer(@producer).to_a
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit; end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(producer_params)

    if @producer.save
      redirect_to @producer, notice: 'Producer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /producers/1
  # PATCH/PUT /producers/1.json
  def update
    if @producer.update(producer_params)
      redirect_to @producer, notice: 'Producer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer.destroy
    redirect_to producers_url, notice: 'Producer was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def at_producer
    @producer = Producer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def producer_params
    params.require(:producer)
          .permit(:name, :address, :zip, :city, :country_id, :notes, :phone,
                  :web, :email)
  end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.erb
<%= form_with(model: producer, local: true) do |form| %>
  <% if producer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producer.errors.count, "error") %> prohibited this producer from being saved:</h2>

      <ul>
      <% producer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <%= render 'countries/country_select', form: form%>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :web %>
    <%= form.text_field :web %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/producers/_producer_select.html.erb
  <div class="field">
    <%= form.label :producer %>
    <%= form.select(:producer_id, @producers.map { |p| [p.name, p.id] }, include_blank: true) %>
  </div>

app/views/producers/_show.html.erb
<div class="group">
  <h2><%= t('activerecord.models.producer', count: 2) %></h2>
  <% if wine.producer %>
  <ul>
    <li><%= link_to wine.producer.name, wine.producer %></li>
    <li><%= t('view.zip_and_city', city: wine.producer.city, zip: wine.producer.zip) %></li>
    <li><%= wine.producer.country.name %></li>
  </ul>
  <% else %>
  <p><%= t('activerecord.models.producer', count: 0) %>.</p>
  <% end %>
</div>

app/views/producers/edit.html.erb
<h2><%= t_title(:edit) %></h2>

<%= render 'form', producer: @producer %>

<%= link_to t_action(:show), @producer %> |
<%= link_to t_action(:index), producers_path %>

app/views/producers/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%= t_title(:index) %></h2>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.producer.name') %></th>
      <th><%= t('activerecord.attributes.producer.adress') %></th>
      <th><%= t('activerecord.attributes.producer.zip') %></th>
      <th><%= t('activerecord.attributes.producer.city') %></th>
      <th><%= t('activerecord.attributes.producer.country') %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @producers.each do |producer| %>
      <tr>
        <td><%= link_to producer.name, producer %></td>
        <td><%= producer.address %></td>
        <td><%= producer.zip %></td>
        <td><%= producer.city %></td>
        <td><%= producer.country.name %></td>
        <td><%= link_to t_action(:edit), edit_producer_path(producer) %></td>
        <td><%= link_to_destroy producer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @producers %>

<%= link_to t_action(:new), new_producer_path %>

app/views/producers/new.html.erb
<h2><%= t_title(:new) %></h2>

<%= render 'form', producer: @producer %>

<%= link_to t_action(:index), producers_path %>

app/views/producers/show.html.erb
<div class="group">
    <h2><%= @producer.name %> (<%= t_title(:show) %>)</h2>

    <ul>
        <% unless @producer.address.empty? && @producer.zip.empty? && @producer.city.empty? %>
        <li>
            <%= t('activerecord.attributes.producer.address') %>: <%= @producer.address %>
            <%= @producer.zip %> <%= @producer.city %>
        </li>
        <%end%>
        <% if @producer.country %>
        <li><%= t('activerecord.attributes.producer.country') %>: <%= @producer.country.name %></li>
        <%end%>
        <% unless @producer.phone.empty? %>
        <li><%= t('activerecord.attributes.producer.phone') %>: <%= @producer.phone %></li>
        <%end%>
        <% unless @producer.web.empty? %>
        <li><%= t('activerecord.attributes.producer.web') %>: <%= link_to h(@producer.web), @producer.web %></li>
        <%end%>
        <% unless @producer.email.empty? %>
        <li><%= t('activerecord.attributes.producer.email') %>: <%= mail_to @producer.email %></li>
        <%end%>
        <% unless @producer.notes.empty? %>
        <li class="notes"><%= t('activerecord.attributes.producer.notes') %>:
            <p><%= simple_format @producer.notes %></p>
        </li>
        <%end%>
    </ul>
</div>

<div class="group">
    <h2><%= t('view.known_wines') %></h2>

    <h3><%= t('view.wines_to_drink') %></h3>
    <% if @millesimes_to_drink.count.positive? %>
    <ul>
        <% @millesimes_to_drink.each do |mil| %>
        <li>
            <% wine = mil.wine %>
            <%= link_to "#{wine.domain} #{human_millesime(mil)}", wine_millesime_path(wine, mil) %>,
            <%= wine.region.name %> <%= wine.color.name %>
        </li>
        <% end %>
    </ul>
    <% else %>
    <p><%= t('view.no_known_wine', model: t('activerecord.models.producer', count: 1)) %></p>
    <% end %>

    <h3><%= t('view.drunk_wines') %></h3>
    <% if @drunk_millesimes.count.positive? %>
    <ul>
        <% @drunk_millesimes.each do |mil| %>
        <li>
            <% wine = mil.wine %>
            <%= link_to "#{wine.domain} #{human_millesime(mil)}", wine_millesime_path(wine, mil) %>,
            <%= wine.region.name %> <%= wine.color.name %>
        </li>
        <% end %>
    </ul>
    <% else %>
    <p><%= t('view.no_drunk_wine', model: t('activerecord.models.producer', count: 1)) %></p>
    <% end %>
</div>

<%= link_to t_action(:edit), edit_producer_path(@producer) %> |
<%= link_to t_action(:index), producers_path %>