config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :dishes do
      member do
        get :select_regions
        post :save_regions
      end
    end
    resources :bottle_racks do
      member do
        post :get_info
      end
    end
    resources :wines do
      resources :millesimes, except: %i[index] do
        resources :wlogs, except: %i[index show] do
          member do
            get :select_rack
            get :select_rack2
            post :save_rack
          end
        end
      end
    end
    resources :providers
    resources :producers
    resources :colors, except: %i[show] do
      collection do
        get :stats
      end
    end
    resources :countries, except: %i[show] do
      collection do
        get :stats
      end
      resources :regions do
        collection do
          get :country_stats
        end
        member do
          get :stats
          post :wine_list_by_color
        end
      end
    end

    get 'admin/main'
    get 'admin/book'
    get 'admin/stats'
    get 'admin/search'
    get 'admin/preferences'
    post 'admin/set_preferences'
    get '/:locale' => 'admin#main'
    root 'admin#main'
  end
end

app/models/millesime.rb
class Millesime < ApplicationRecord
  DRINK_DIFF = "(millesimes.garde + millesimes.year - cast(strftime('%Y', date('now')) AS integer))".freeze
  DRINK_DIFF_SELECT = (new.attributes.keys.map { |attr| "millesimes.#{attr}" }.join(', ') +
                       ", #{DRINK_DIFF} AS diff").freeze

  belongs_to :wine, required: false
  has_many :wlogs
  accepts_nested_attributes_for :wlogs
  has_many :bottles

  validates :year, presence: true,
                   numericality: { only_integer: true },
                   uniqueness: { scope: :wine_id },
                   allow_nil: true
  validates :garde, presence: { if: :garde_required? },
                    numericality: { only_integer: true, if: :garde_required? }

  # Cannot define it with scope!
  def self.from_region(region)
    joins(wine: :region).where(wines: { region: region.id })
  end

  def self.from_regions(regions)
    joins(wine: :region).where(wines: { region: regions })
  end

  scope :from_producer, ->(prod) { joins(:wine).where(wines: { producer: prod.id }) }
  scope :from_provider, ->(prov) { joins(:wine).where(wines: { provider: prov.id }) }
  scope :with_bottles, -> { joins(:bottles).distinct }

  # Cannot define it with scope!
  def self.without_bottles
    left_outer_joins(:bottles).distinct
                              .unscope(:select)
                              .group('millesimes.id')
                              .having('COUNT(bottles.id) == 0')
  end

  # Need to use DRINK_DIFF, and not diff here, as select may be overwritten (this is the case when count on a column)
  scope :drink_before, ->(years) { select(DRINK_DIFF_SELECT).where.not(year: nil).where("#{DRINK_DIFF} < ?", years) }
  scope :drink_after, ->(years) { select(DRINK_DIFF_SELECT).where.not(year: nil).where("#{DRINK_DIFF} >= ?", years) }

  scope :of_color, ->(color) { joins(wine: [:color]).where(wines: { color: color.id }) }
  scope :by_year, -> { order(:year) }

  def quantity
    Millesime.joins(:bottles).where(id: id).count
  end

  # Give years before wine is at its culmination
  def years_to_drink_wine
    year + garde - Time.now.year
  end

  def void_millesime
    year.nil?
  end

  private

  def garde_required?
    !year.nil?
  end
end

app/controllers/millesimes_controller.rb
class MillesimesController < ApplicationController
  before_action :at_wine
  before_action :at_millesime, only: %i[show edit update destroy]

  def show
    @racks = BottleRack.millesime(@millesime).all
    @dras = @millesime.wine.region.dras.of_color(@millesime.wine.color).by_dishes
  end

  def new
    @millesime = @wine.millesimes.build
  end

  def edit; end

  def create
    @millesime = @wine.millesimes.build(millesime_params)

    if @millesime.save
      redirect_to [@millesime.wine, @millesime], notice: 'Millesime was successfully created.'
    else
      render :new
    end
  end

  def update
    if @millesime.update(millesime_params)
      redirect_to [@wine, @millesime], notice: 'Millesime was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @millesime.destroy
    redirect_to wine_url(@wine), notice: 'Millesime was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def at_millesime
    @millesime = @wine.millesimes.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def millesime_params
    p = params.require(:millesime).permit(:year, :garde, :wine_id, :notes)
    if params[:millesime][:void_millesime] == 1
      p[:millesime][:year] = nil
      p[:millesime][:garde] = nil
    end

    p
  end
end

app/helpers/millesimes_helper.rb
module MillesimesHelper
end

app/views/millesimes/_form.html.erb
<% if !subform && @millesime.errors.any? %>
  <div id="error_explanation">
    <% count = @millesime.errors.count %>
    <h2><%= t('form.cannot_save', model: t('activerecord.models.millesime', count: count), count: count) %></h2>
    <ul>
    <% @millesime.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :void_millesime, t('view.millesime.void') %>
  <%= form.check_box :void_millesime %>
</div>

<div class="field">
  <%= form.label :year %>
  <%= form.number_field :year %>
</div>

<div class="field">
  <%= form.label :garde %>
  <%= form.text_field :garde %>
</div>

<div class="field">
  <%= form.label :notes %>
  <%= form.text_area :notes %>
</div>

<% if @millesime.new_record? %>
  <h2><%= t('activerecord.models.wlog', count: 1) %></h2>
  <%= form.fields_for(:wlogs) do |fw| %>
    <%= render partial: 'wlogs/form', locals: { subform: true, form: fw } %>
  <% end %>
<% end %>

<% unless subform %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/millesimes/edit.html.erb
<h1><%= t_title(:edit) %></h1>

<div class="group">
  <%= render partial: 'wines/wine', locals: { wine: @wine, min: true } %>
</div>

<%= form_with(model: [@wine, @millesime], local: true) do |form| %>
  <%= render partial: 'form', locals: { subform: false, form: form } %>
<% end %>

<%= link_to t_action(:index), wine_path(@wine) %>

app/views/millesimes/new.html.erb
<h1><%= t_title(:new) %></h1>

<div class="group">
  <%= render partial: 'wines/wine', locals: { wine: @wine, min: true } %>
</div>

<%= form_with(model: [@wine, @millesime], local: true) do |form| %>
  <%= render partial: 'form', locals: { subform: false, form: form } %>
<% end %>

<%= link_to t_action(:show), wine_path(@wine) %>

app/views/millesimes/show.html.erb
<div class="group">
    <h2><%= @millesime.wine.domain %> <%= human_millesime(@millesime) %> (<%= t_title(:show) %>)</h2>

    <%= render partial: 'wines/wine', locals: { wine: @wine, min: true } %>

    <ul>
        <% if @millesime.garde %>
        <li><%= t('activerecord.attributes.millesime.garde') %>: <%= @millesime.garde %></li>
        <% end %>
        <li><%= t('activerecord.attributes.wlog.quantity') %>: <%= @millesime.quantity %></li>
        <li>
            <%= t('activerecord.models.bottle_rack', count: 2) %>:
            <% if @racks.empty? %>
            <%= t('activerecord.models.bottle_rack', count: 0) %>
            <% else %>
            <ul>
                <% @racks.each do |rack| %>
                <li>
                    <%= link_to rack.name, bottle_rack_path(rack)%>:
                    <%= BottleRack.ary_to_pos(rack.bottles.map(&:pos).sort) %>
                </li>
                <% end %>
            </ul>
            <% end %>
        </li>
    </ul>

    <% if @wine.attribute_present? :notes %>
    <dl>
        <dt><%= t('view.notes_about_wine') %></dt>
        <dd><%= simple_format @wine.notes %></dd>
    </dl>
    <% end %>
    <% if @millesime.attribute_present? :notes %>
    <dl>
        <dt><%= t('view.notes_about_millesime') %></dt>
        <dd><%= simple_format @millesime.notes %></dd>
    </dl>
    <% end %>
</div>

<%= render partial: 'producers/show', locals: { wine: @wine } %>
<%= render partial: 'providers/show', locals: { wine: @wine } %>

<div class="group">
    <h2><%= t('view.millesime.associated_dishes') %></h2>
    <% if @dras.empty? %>
    <p><%= t('activerecord.models.dish', count: 0) %></p>
    <% else %>
    <p><%= t('view.millesime.associated_dishes_intro') %></p>
    <ul class="dishes">
        <% @dras.each do |dra| %>
        <li>
            <%= link_to dra.dish.name, dish_path(dra.dish) %>
        </li>
        <% end %>
    </ul>
    <% end %>
</div>

<div class="group">
    <h2><%= t('activerecord.models.wlog', count: 2) %></h2>
    <%= render 'wlogs/wlogs' %>
    <%= link_to t_action(:new, Wlog), new_wine_millesime_wlog_path(@wine, @millesime) %>
</div>

<%= link_to t_action(:edit), edit_wine_millesime_path(@wine, @millesime) %> |
<%= link_to t('activerecord.models.wine', count: 1), wine_path(@wine) %>