config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :dishes do
      member do
        get :select_regions
        post :save_regions
      end
    end
    resources :bottle_racks do
      member do
        post :get_info
      end
    end
    resources :wines do
      resources :millesimes, except: %i[index] do
        resources :wlogs, except: %i[index show] do
          member do
            get :select_rack
            get :select_rack2
            post :save_rack
          end
        end
      end
    end
    resources :providers
    resources :producers
    resources :colors, except: %i[show] do
      collection do
        get :stats
      end
    end
    resources :countries, except: %i[show] do
      collection do
        get :stats
      end
      resources :regions do
        collection do
          get :country_stats
        end
        member do
          get :stats
          post :wine_list_by_color
        end
      end
    end

    get 'admin/main'
    get 'admin/book'
    get 'admin/stats'
    get 'admin/search'
    get 'admin/preferences'
    post 'admin/set_preferences'
    get '/:locale' => 'admin#main'
    root 'admin#main'
  end
end

app/models/region.rb
class Region < ApplicationRecord
  acts_as_nested_set scope: :country

  validates_presence_of :name, :country_id

  belongs_to :country
  has_many :wines
  has_many :dras
  has_many :dishes, through: :dras
  has_and_belongs_to_many :colors

  scope :by_country, ->(country_id) { where('regions.country_id = ?', country_id) }
  scope :by_name, -> { order(:name) }

  def direct_descendants
    Region.children_of(self.id)
  end

  def all_descendants
    Region.left_of(self.rgt).right_of(self.lft)
  end

  def color?(color)
    colors.where(id: color.id).count.positive?
  end

  def dishes_by_color(color)
    dras.by_regions.of_color(color).map(&:dish)
  end
end

app/controllers/regions_controller.rb
require 'select_type'

class RegionsController < ApplicationController
  before_action :at_country
  before_action :at_regions, only: %i[new edit]
  before_action :at_region, only: %i[show edit update destroy stats wine_list_by_color]
  before_action :at_countries, only: %i[new create edit update]

  def index; end

  def show
    wine_order = 'wines.domain, millesimes.year'
    region_order = "regions.name, #{wine_order}"
    @millesimes = Millesime.from_region(@region)
                           .with_bottles
                           .order(wine_order)
    @others_millesimes = Millesime.from_regions(@region.all_descendants)
                                  .with_bottles
                                  .order(region_order)
    @drunk_millesimes = Millesime.from_region(@region)
                                 .without_bottles
                                 .order(wine_order)
    @others_drunk_millesimes = Millesime.from_regions(@region.all_descendants)
                                        .without_bottles
                                        .order(region_order)
  end

  def new
    @region = @country.regions.build
  end

  def edit; end

  def create
    @region = @country.regions.build(region_params)

    if @region.save
      redirect_to [@region.country, @region],
                  notice: 'Region was successfully created.'
    else
      set_regions @country.id
      render action: 'new'
    end
  end

  def update
    if @region.update_attributes(region_params)
      redirect_to [@region.country, @region],
                  notice: 'Region was successfully updated.'
    else
      set_regions @country.id
      render action: 'edit'
    end
  end

  def destroy
    @region.destroy

    redirect_to country_regions_url(@country)
  end

  def country_stats
    compute_statistics_on_wines(Wine.from_country(@country), &:root)
    # Sort @regions hash alphabetically by keys
    @regions = @regions.sort_by { |key| key }.to_h
  end

  def stats
    subregions = @region.children
    if subregions.empty?
      @regions = {}
      return
    end

    subregions += [@region]
    wines = Wine.from_region_and_its_descendant(@region)
    compute_statistics_on_wines(wines) do |region|
      region.self_and_ancestors.reverse.find { |r| subregions.include?(r) }
    end
  end

  # Ajax only
  def wine_list_by_color
    color = Color.find(params[:color_id])
    wines = Millesime.from_region(@region).of_color(color).by_year.with_bottles
    render partial: 'wine_list_by_color', layout: false, locals: { wines: wines }
  end

  private

  def at_country
    @country = Country.find(params[:country_id])
  end

  def at_countries
    @countries = Country.by_name
  end

  def at_region
    @region = @country.regions.find(params[:id])
  end

  def region_params
    params.require(:region)
          .permit(:name, :parent_id, :country_id, color_ids: [])
  end

  def clean_and_compute_percentages
    @regions.each_key do |k|
      if @regions[k][:nb].zero?
        @regions.delete(k)
      else
        @regions[k][:p] = @regions[k][:nb].to_f / @sum_regions * 100
      end
    end
  end

  def compute_statistics_on_wines(wines)
    @regions = {}
    @sum_regions = 0

    wines.each do |wine|
      ref_region = yield wine.region
      rr_name = ref_region.name
      @regions[rr_name] = init_region_stat(ref_region) unless @regions.key?(rr_name)
      @regions[rr_name][:nb] += wine.quantity
      @sum_regions += wine.quantity
    end

    clean_and_compute_percentages
  end

  def init_region_stat(region)
    { nb: 0, p: 0.0, id: region.id }
  end
end

app/helpers/regions_helper.rb
module RegionsHelper
  def link_to_region(region)
    link_to region.name, country_region_path(region.country, region)
  end

  def generate_region_tree(country)
    content_tag(:ul, class: 'treeview') do
      tree_from country.regions.roots.by_name
    end
  end

  private

  def tree_from(nodes)
    out = +''

    nodes.each do |node|
      descendants = node.direct_descendants.by_name
      out << content_tag(:li) do
        if descendants.count.positive?
          out2 = content_tag(:span, link_to_region(node), class: 'caret')
          out2 << content_tag(:ul, class: 'nested') do
            tree_from descendants
          end
        else
          content_tag(:span, link_to_region(node), class: 'no-caret')
        end
      end

      out << "\n"
    end

    raw out
  end
end

app/views/regions/_form.html.erb
<%= form_with(model: [@region.country, @region]) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <% count = @region.errors.count %>
      <h2><%= t('form.cannot_save', model: t('activerecord.models.region', count: count), count: count) %></h2>
      <ul>
      <% @region.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

   <div class="field">
    <%= f.label :color %>
    <%= f.collection_check_boxes :color_ids, Color.by_name.all, :id, :name do |b|%>
    <% b.label(class: 'inline') + b.check_box + raw('&nbsp;&nbsp;') %>
    <% end %>
  </div>


  <div class="field">
    <%= f.label :parent %>
    <%= f.select(:parent_id, nil, {}, {size: 10}) do %>
      <%= option_groups_from_collection_for_select(@regions, :options, :type_name, :id, :name, @region.parent_id) %>
    <% end %>
  </div>

  <%= render 'countries/country_select', form: f %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/_region_select.html.erb
  <div class="field">
    <%= form.label :region %>
    <%= form.select(:region_id, nil, {}, {size: 10}) do %>
      <%= option_groups_from_collection_for_select(@regions, :options, :type_name, :id, :name, @wine.region_id) %>
    <% end %>
  </div>

app/views/regions/_wine_list.html.erb
  <% if wines.empty? and others_wines.empty? %>
  <%= t('activerecord.models.wine', count: 0) %>
  <% else %>
  <ul class="ungroup">
      <% wines.each do |millesime| %>
      <li>
          <%= link_to "#{millesime.wine.domain} #{human_millesime(millesime)}", wine_millesime_path(millesime.wine, millesime) %>,
          <%= millesime.wine.color.name %>
      </li>
      <% end %>
      <% others_wines.each do |millesime| %>
      <li>
          <%= link_to "#{millesime.wine.domain} #{human_millesime(millesime)}", wine_millesime_path(millesime.wine, millesime) %>,
          <%= millesime.wine.color.name %> (<%= millesime.wine.region.name %>)
      </li>
      <% end %>
  </ul>
  <% end %>

app/views/regions/_wine_list_by_color.html.erb
<% wines.each do |mil| %>
  <li>
    <%= link_to "#{mil.wine.domain} #{human_millesime(mil)}", wine_millesime_path(mil.wine, mil) %>
    (<%= pluralize(mil.quantity, 'bottle') %>)
  </li>
<% end %>

app/views/regions/country_stats.html.erb
<h2><%= t('view.statistic.country_title', country: @country.name) %></h2>

<table class="stat">
    <thead>
        <tr>
            <th><%= t('activerecord.models.region', count: 1) %></th>
            <th><%= t('view.statistic.nb_bottles') %></th>
            <th><%= t('view.statistic.percentage') %></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td><%= t('view.statistic.sum') %></td>
            <td class="right"><%= @sum_regions %></td>
            <td class="right">100.0%</td>
        </tr>
    </tfoot>
    <tbody>
        <% @regions.each do |region, data| %>
        <tr>
            <td><%= link_to region, country_region_path(@country, data[:id]) %></td>
            <td class="right"><%= data[:nb] %></td>
            <td class="right"><%= sprintf("%.1f%%", data[:p]) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= pie_chart Hash[@regions.map { |name, data| [name, data[:nb]] }] %>

<%= link_to t_action(:index), country_regions_path(@country) %>
|
<%= link_to t('view.statistics'), controller: 'admin', action: 'stats' %>

app/views/regions/edit.html.erb
<h2><%= @country.name %> &gt; <%= t_title(:edit) %></h2>

<%= render 'form' %>

<%= link_to t_action(:show), [@region.country, @region] %> |
<%= link_to t_action(:index), country_regions_path(@region.country) %>

app/views/regions/index.html.erb
<h2><%= @country.name %> &gt; <%= t_title(:index) %></h2>

<%= generate_region_tree(@country) %>

<%= link_to t_action(:new), new_country_region_path(@country) %> |
<%= link_to t('view.statistics'), country_stats_country_regions_path(@country) %>

app/views/regions/new.html.erb
<h2><%= @country.name %> &gt; <%= t_title(:new) %></h2>

<%= render 'form' %>

<%= link_to t_action(:index), country_regions_path(@region.country) %>

app/views/regions/show.html.erb
<div class="group">
  <h2><%= @country.name %> &gt; <%= @region.name %></h2>

  <ul>
    <% unless @region.root? %>
    <li><%= t('region.zone') %>: <%= link_to @region.root.name, country_region_path(@country, @region.root) %></li>
    <li><%= t('activerecord.attributes.region.parent') %>: <%= link_to @region.parent.name, country_region_path(@country, @region.parent) %></li>
    <% end %>
    <li><%= t('activerecord.attributes.region.country') %>: <%= link_to @region.country.name, country_regions_path(@country) %></li>
    <li><%= t('activerecord.attributes.region.colors') %>: <%= @region.colors.map(&:name).join(', ') %></li>
  </ul>

  <% unless @region.leaf? %>
  <h3><%= t('view.region.subregions') %></h3>
  <ul class="ungroup">
  <% @region.children.each do |child| %>
    <li><%= link_to child.name, country_region_path(@country, child) %></li>
  <% end %>
  </ul>
  <% end %>
</div>

<div class="group">
  <h2><%= t('view.known_wines') %></h2>

  <%= t('view.wines_to_drink') %>:
  <%= render partial: 'wine_list', locals: { wines: @millesimes, others_wines: @others_millesimes } %>

  <br/>
  <%= t('view.drunk_wines') %>:
  <%= render partial: 'wine_list', locals: { wines: @drunk_millesimes, others_wines: @others_drunk_millesimes } %>
</div>

<div class="group">
  <h2><%= t('view.region.associated_dishes') %></h2>
  <% @region.colors.by_name.each do |color| %>
    <% dishes = @region.dishes_by_color(color) %>
    <% unless dishes.empty? %>
      <h3><%= color.name %></h3>
      <ul>
        <% dishes.each do |dish| %>
          <li><%= link_to dish.name, dish_path(dish) %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

<%= link_to t_action(:edit), edit_country_region_path(@country, @region) %> |
<%= link_to t_action(:index), country_regions_path(@country) %> |
<%= link_to t('view.region.region_stats'), stats_country_region_path(@country, @region) %> |
<%= link_to_destroy [@country, @region], no_img: true %>

app/views/regions/stats.html.erb
<h2><%= @country.name %> &gt; <%= t('view.statistic.region_title', region: @region.name) %></h2>

<% unless @regions.empty? %>
<table class="stat">
    <thead>
        <tr>
            <th><%= t('activerecord.models.region', count: 1) %></th>
            <th><%= t('view.statistic.nb_bottles') %></th>
            <th><%= t('view.statistic.percentage') %></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td><%= t('view.statistic.sum') %></td>
            <td class="right"><%= @sum_regions %></td>
            <td class="right">100.0%</td>
        </tr>
    </tfoot>
    <tbody>
        <% @regions.each do |region, data| %>
        <tr>
            <td><%= link_to region, country_region_path(@country, data[:id]) %></td>
            <td class="right"><%= data[:nb] %></td>
            <td class="right"><%= sprintf("%.1f%%", data[:p]) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= pie_chart Hash[@regions.map { |name, data| [name, data[:nb]] }] %>
<% else %>
<p><%= t('view.region.no_stats') %></p>
<% end %>

<%= link_to t('activerecord.models.region', count: 1), country_region_path(@country, @region) %>
|
<%= link_to t('view.statistics'), controller: 'admin', action: 'stats' %>