config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
    resources :dishes do
      member do
        get :select_regions
        post :save_regions
      end
    end
    resources :bottle_racks do
      member do
        post :get_info
      end
    end
    resources :wines do
      resources :millesimes, except: %i[index] do
        resources :wlogs, except: %i[index show] do
          member do
            get :select_rack
            get :select_rack2
            post :save_rack
          end
        end
      end
    end
    resources :providers
    resources :producers
    resources :colors, except: %i[show] do
      collection do
        get :stats
      end
    end
    resources :countries, except: %i[show] do
      collection do
        get :stats
      end
      resources :regions do
        collection do
          get :country_stats
        end
        member do
          get :stats
          post :wine_list_by_color
        end
      end
    end

    get 'admin/main'
    get 'admin/book'
    get 'admin/stats'
    get 'admin/search'
    get 'admin/preferences'
    post 'admin/set_preferences'
    get '/:locale' => 'admin#main'
    root 'admin#main'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cavavin2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <h1>Cavavin2</h1>
    </div>

    <div id="content">
      <div id="sidebar">
        <div class="menu">
          <h4><%= t('view.menu') %></h4>
          <ul>
            <li><%= link_to t('view.homepage'), admin_main_path %></li>
            <li><%= link_to t('view.cellar_book'), admin_book_path %></li>
            <li class="separator"></li>
            <li><%= link_to t('activerecord.models.wine', count: 2), wines_path %></li>
            <li><%= link_to t('activerecord.models.producer', count: 2), producers_path %></li>
            <li><%= link_to t('activerecord.models.provider', count: 2), providers_path %></li>
            <li><%= link_to t('activerecord.models.dish', count: 2), dishes_path %></li>
            <li><%= link_to t('activerecord.models.country', count: 2), countries_path %></li>
            <li><%= link_to t('activerecord.models.color', count: 2), colors_path %></li>
            <li><%= link_to t('activerecord.models.bottle_rack', count: 2), bottle_racks_path %></li>
            <li class="separator"></li>
            <li><%= link_to t('view.statistics'), admin_stats_path %></li>
            <li><%= link_to t('activerecord.models.preference', count: 2), admin_preferences_path %></li>
          </ul>
        </div>
        <div class="menu search">
          <h4><%= t('view.search') %></h4>
          <%= form_tag(admin_search_path, method: 'get') do %>
            <%= text_field_tag 'search', params[:search] %>
            <%= submit_tag t('form.search') %>
          <% end %>
        </div>
      </div>

      <div id="real-content">
        <% if flash[:notice] %>
          <p id="notice"><%= notice %></p>
        <% elsif flash[:alert] %>
          <p id="alert"><%= t('view.flash.error', msg: alert) %></p>
        <% end %>

        <%= yield %>
      </div>
    </div>

    <div id="footer">
    </div>
  </body>
</html>